/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package consecionario;

import Coneccion.CRUD_Persona;
import Controller.controllerPersona;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import util.SesionUsuario;
import Modelo.Persona;

/**
 *
 * @author willi
 */
public class Loggin extends javax.swing.JPanel {

    /**
     * Creates new form Loggin
     */
    private controllerPersona personaController;

    public Loggin() {
        initComponents();
        personaController = new controllerPersona();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TUser = new javax.swing.JTextField();
        TPassword = new javax.swing.JPasswordField();
        Loggin = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        jLabelUserName = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        TUser.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUserActionPerformed(evt);
            }
        });

        TPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPasswordActionPerformed(evt);
            }
        });

        Loggin.setText("Iniciar Sesion");
        Loggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogginActionPerformed(evt);
            }
        });

        Registrar.setText("Registrar");
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarMouseClicked(evt);
            }
        });
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        jLabelUserName.setText("Usuario");

        jLabelPassword.setText("Password");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setText("Loggin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(TUser, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(Loggin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword))
                .addGap(18, 18, 18)
                .addComponent(Loggin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Registrar)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TUserActionPerformed

    private void TPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPasswordActionPerformed

    private void LogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogginActionPerformed
        // TODO add your handling code here:
        logginUsuario();
    }//GEN-LAST:event_LogginActionPerformed

    private void RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseClicked
        // TODO add your handling code here:
        registarUsuario();
    }//GEN-LAST:event_RegistrarMouseClicked

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RegistrarActionPerformed

    public void limpiarCampos(){
        TUser.setText("");
        TPassword.setText("");
    }
   


    public void registarUsuario(){
        try {
            int id = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Id"));
            String nombre = JOptionPane.showInputDialog("Ingrese el Nombre");
            String apellido = JOptionPane.showInputDialog("Ingrese el apellido");
            String telefono = JOptionPane.showInputDialog("Ingrese el Telefono");
            String correo = JOptionPane.showInputDialog("Ingrese el Correo");
            String nombreUsuario = JOptionPane.showInputDialog("Ingrese el nombre de usuario");
            String password = JOptionPane.showInputDialog("Ingrese el Password");
            CRUD_Persona c = new CRUD_Persona();
            // Primero insertamos en la tabla persona
            int resultPersona = c.guardarCliente(id, nombre, apellido, telefono, correo);
            if (resultPersona > 0) {
                // Si se insertó correctamente la persona, insertamos el vendedor
                int resultVendedor = c.registrarVendedor(id, nombreUsuario, password);
                if (resultVendedor > 0) {
                    JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al registrar las credenciales del vendedor");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar los datos personales");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número válido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage());
        }
    }
   
    public void logginUsuario() {
        String nombreUsuario = TUser.getText();
        String password = new String(TPassword.getPassword());
        if (nombreUsuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos");
            return;
        }
        try {
            Persona usuario = personaController.loginVendedorYObtenerDatos(nombreUsuario, password);
            if (usuario != null) {
                SesionUsuario.setDatos(usuario.getId(), usuario.getNombre(), usuario.getApellido(), usuario.getEmail());
                frmConcesionario concesionario = new frmConcesionario();
                concesionario.setVisible(true);
                javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Usuario o contraseña incorrectos\nVerifique sus credenciales e intente nuevamente", 
                    "Error de autenticación", 
                    JOptionPane.ERROR_MESSAGE);
                TPassword.setText("");  // Limpiar solo la contraseña por seguridad
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Error al intentar iniciar sesión: " + e.getMessage() + 
                "\nPor favor, contacte al administrador del sistema", 
                "Error de sistema", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loggin;
    private javax.swing.JButton Registrar;
    private javax.swing.JPasswordField TPassword;
    private javax.swing.JTextField TUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserName;
    // End of variables declaration//GEN-END:variables
}
